### ISSUE TITLE
Error: The DMN EvalResults could not be loaded.

### ISSUE THREAD

**Issue by pblumer** [camunda-community-hub/camunda-dmn-tester#1] opened 2021-05-04 06:54 UTC
Hi
I'm trying to use the dmn-tester with docker and get the following Error:
Error: The DMN EvalResults could not be loaded. (Problem running the Tests: org.scalajs.dom.ext.AjaxException)

Let's start

[scala-execution-context-global-28] INFO o.c.f.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(org.camunda.dmn.NoUnpackValueMapper@71c8ee5a)), function-provider: org.camunda.feel.context.FunctionProvider$EmptyFunctionProvider$@31b50079, clock: SystemClock, configuration: Configuration(false)]

From Docker-Log:

> Start testing evaluate_change_template_name: List(dmns, evaluate_phase_out_change_template.dmn) (/opt/docker/dmns/evaluate_phase_out_change_template.dm
> Fiber failed.
> An unchecked error was produced.
> java.lang.NullPointerException
> at org.camunda.dmn.parser.DmnParser.parseFeelExpression(DmnParser.scala:381)
> at org.camunda.dmn.parser.DmnParser.$anonfun$parseDecisionTable$1(DmnParser.scala:199)
> at scala.collection.StrictOptimizedIterableOps.map(StrictOptimizedIterableOps.scala:99)
> at scala.collection.StrictOptimizedIterableOps.map$(StrictOptimizedIterableOps.scala:86)
> at scala.collection.convert.JavaCollectionWrappers$JCollectionWrapper.map(JavaCollectionWrappers.scala:68)
> at org.camunda.dmn.parser.DmnParser.parseDecisionTable(DmnParser.scala:196)
> at org.camunda.dmn.parser.DmnParser.parseDecision(DmnParser.scala:109)
> at org.camunda.dmn.parser.DmnParser.$anonfun$parseModel$3(DmnParser.scala:81)
> at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:454)

Anyone any idea if I'm doing something wrong?

**Comment by pme123** [comment] 2021-05-04 15:05
Hi @pblumer 
Do you have a Screen Shot of the DMN Tester - or better can you share your dmn - then I can try to reproduce your problem.

**Comment by pblumer** [comment] 2021-05-05 09:27
Hi @pme123 
as you wish a screenshot and the dmn file:
![dmn_table_tester_screenshot](https://user-images.githubusercontent.com/34165194/117120016-16d83d00-ad93-11eb-89e6-e3d5b92f7a58.jpg)

The DMN-File:
[evaluate_phase_out_change_template.zip](https://github.com/pme123/camunda-dmn-tester/files/6426105/evaluate_phase_out_change_template.zip)
I have to zip it for upload...

thanks in advance

**Comment by pme123** [comment] 2021-05-05 10:54
Hi @pblumer 

ok - the problem is the second table which has no valid inputs defined - turns out that is a problem for dmn-scala the Dmn Engine. 

If you fix that - you have a second problem. The input variable must be defined in the expression. The 'input variable' in this context means something different (I have actually forgotten what it is ;().
![image](https://user-images.githubusercontent.com/3437927/117130585-8ef92f80-ada0-11eb-89d3-3463648f186d.png)

**Comment by pme123** [comment] 2021-05-10 18:05
This will be fixed in dmn-scala with this: https://github.com/camunda-community-hub/dmn-scala/pull/27

**Closed as completed by pme123** 2021-05-10 18:05 UTC
